### ISSUE TITLE
SE.Halligang\XmpToolkit\XmpToolkit.sln and compile 

### ISSUE THREAD

**Issue by sour7230** [Metrilus/xmp-sharp#3]
SE.Halligang\XmpToolkit\XmpToolkit.sln and compile when i  getting this type of error

![image](https://user-images.githubusercontent.com/26112010/34459797-512045d8-ee20-11e7-85a7-411a4cdd41bd.png)

**Comment by f00f** [comment]
Please follow the instructions in the Readme file:

> Copy the generated .lib files (e.g. XMPCoreStaticRelease64.lib and XMPFilesStaticRelease64.lib from XMP-SDK\public\libraries\windows_x64\release\) to SE.Halligang\XmpToolkit\lib\.

If you want to compile Debug you have to copy the Debug .lib files.
